on:
  push:
    branches:
      - dev
name: Deploy website (dev) over SFTP
jobs:
  deploy_job:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy file(s)
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: thrain.dreamhost.com
        # server: dev.sammyharper.com
        username: samharp_admin
        password: ${{ secrets.sftp_password }}
        port: 22
        local_path: './*'
        remote_path: '/home/samharp_admin/dev.sammyharper.com/'